### ISSUE TITLE
10-31-2023 Spooky Suggestions

### ISSUE THREAD

**Issue by Xander8** [VancouverBitdevs/VancouverBitdevs.github.io#45]
Hey gents & gals,

Please post links of your topics you'd like to discuss at our upcoming BitDevs! Post them in the comments section below.

Ideally in this format:

```
[BRIEF DESCRIPTION OF TOPIC ](http://putYourLinkHere.ca)
```

**Comment by Liongrass** [comment]
# Whitepaper special

[Satoshi's Vision](https://github.com/JeremyRubin/satoshis-version)

[The Story Behind the Alternative Genesis Block of Bitcoin](https://serhack.me/articles/story-behind-alternative-genesis-block-bitcoin/)

[static const int64 COIN = 1000000;](https://github.com/chillininvt/OriginalBitcoin/blob/main/main.h#L34)

[int64 nSubsidy = 10000 * CENT;](https://github.com/chillininvt/OriginalBitcoin/blob/main/main.cpp#L654)

[const unsigned int nTargetTimespan = 30 * 24 * 60 * 60;](https://github.com/chillininvt/OriginalBitcoin/blob/main/main.cpp#L662)

[const unsigned int nTargetSpacing = 15 * 60;](https://github.com/chillininvt/OriginalBitcoin/blob/main/main.cpp#L655)

[The timechain is a tree shaped structure](https://github.com/chillininvt/OriginalBitcoin/blob/23e059927870f84bbf1081953e4edc1e89ead6a1/main.h#L919C44-L919C44)

# Regular Bitdevs

[MEV on Bitcoin has arrived](https://twitter.com/niftynei/status/1705662689639350588)

[Runes](https://rodarmor.com/blog/runes/)

[Send satograms over the Lightning Network](https://satogram.xyz/)

[LN+ Liquidity Pool](https://lightningnetwork.plus/posts/433)

[MARA mined an invalid block again](https://twitter.com/bitmexresearch/status/1706966754331652164)

[BRC-20 griefing attack](https://twitter.com/rodarmor/status/1705369258426036526)

[Covenant tools softfork pull request](https://github.com/bitcoin/bitcoin/pull/28550)

[Spotlight: Langley Bitcoin Meetup](https://twitter.com/joshuafriedeman/status/1707786119331406195)

[Bank of Canada cashless survey](https://twitter.com/bankofcanada/status/1707772358793077050)

[Phoenix splicing rolls out for all users on iOS and Android](https://x.com/phoenixwallet/status/1708055031398711478)

[Opinion: Washington is quickly hurtling toward a debt crisis](https://www.cnn.com/2023/09/29/opinions/federal-debt-interest-rates-riedl/index.html)

[Mempool almost cleared](https://twitter.com/mempool/status/1708618638800945395)

[Bitcoin Payment Service BTCPay Server Now Easier to Integrate with React Apps](https://bitcoinmagazine.com/technical/bitcoin-payment-service-btcpay-server-now-easier-to-integrate-with-react-apps)

[GPU marketplace open-sources codebase and launches 1 BTC bounty](https://gputopia.ai/blog/opening)

[What Bitcoin Did: Decentralise Everything with William Casarin](https://www.whatbitcoindid.com/podcast/decentralise-everything)

[LNbits Node Manager released](https://x.com/callebtc/status/1709883171968291017)

[FTX insurance fund was fake](https://twitter.com/molly0xfff/status/1710718416724595187)

[Out of 763,130 Lightning payments made by Wallet of Satoshi, 684,120 had no fees](https://x.com/walletofsatoshi/status/1711208926727885153)

[BitVM: Compute Anything on Bitcoin](https://bitvm.org/bitvm.pdf)

[Wallet Fingerprints: Detection & Analysis](https://ishaana.com/blog/wallet_fingerprinting/)

[The Lightning Network Grew by 1212% in 2 Years](https://blog.river.com/the-lightning-network-in-2023/)

[Instantly simulate real-world Lightning network activity](https://simln.dev/)

[Unlocking Bitcoin: Bridging Gaps for Mainstream Adoption with Adam Soltys, Coinos Founder](https://www.youtube.com/watch?v=5rljilNANCw)

[Peter Todd's Drivechains Critique](https://petertodd.org/2023/drivechains)

[Replacement Cycling Attacks on the Lightnin Network](https://github.com/ariard/mempool-research/blob/2023-10-replacement-paper/replacement-cycling.pdf)

[Settings to force anchor channels only that rejects legacy channels](https://github.com/lightningnetwork/lnd/issues/8075)

[The secret life of Jimmy Zhong, who stole – and lost – more than $3 billion](https://www.cnbc.com/2023/10/17/crypto911.html)

[LND Speed Run 🏃](https://www.youtube.com/watch?v=9svP0Fpp1ZQ)

[Timeout Trees: A Solution To Scaling Lightning Network LSPs](https://bitcoinmagazine.com/technical/timeout-trees-a-solution-to-scaling-lightning-network-lsps)

[Removing channel reserve for mobile wallet users](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-October/004136.html)

[Lightning Labs Rolls Out Taproot Assets Mainnet Alpha](https://bitcoinmagazine.com/technical/lightning-labs-rolls-out-taproot-assets-mainnet-alpha)

[Inside a $30 Million Cash-for-Bitcoin Laundering Ring in the Heart of New York](https://www.404media.co/inside-a-30-million-cash-for-bitcoin-laundering-ring-in-the-heart-of-new-york/)

[Premise announces partnership with Neutronpay](https://finance.yahoo.com/news/premise-announces-partnership-neutronpay-premier-110700552.html)

[Hal Finney Was Not Satoshi Nakamoto](https://blog.lopp.net/hal-finney-was-not-satoshi-nakamoto/)

[New BIP: Ordinal Numbers #1408](https://github.com/bitcoin/bips/pull/1408)

[BitVM Primer](https://github.com/twhit223/bitvm_primer)

[A bathhouse that mines Bitcoin](https://x.com/parismartineau/status/1716862159542493295)

[They Cracked the Code to a Locked USB Drive Worth $235 Million in Bitcoin. Then It Got Weird](https://www.wired.com/story/unciphered-ironkey-password-cracking-bitcoin/)

[Universal Money Addresses by Lightspark](https://www.lightspark.com/uma)

[Autozaps in Zapple Pay](https://x.com/benthecarman/status/1716920700081254840)

[Neutronpay Cash Out Solution](https://twitter.com/neutronpay/status/1716840168383234298)

[The ZEUS v0.8.0 open beta is here](https://blog.zeusln.com/zeus-v0-8-0-open-beta/)

[Ray Youssef: The Ray Narrative](https://bitcoinmagazine.com/business/the-ray-narrative)

**Comment by Liongrass** [comment]
Closing this issue! Thank you for all the contributions!
