### ISSUE TITLE
2024-01-30 Get your links and discussion topics in!

### ISSUE THREAD

**Issue by Liongrass** [VancouverBitdevs/VancouverBitdevs.github.io#53]
Feel free to add all your discussion links, Ideally formatted as a link. Markdown can help.

**Comment by Liongrass** [comment]
[Mempool sniping of ordinals purchases](https://x.com/huuep/status/1729559294289600755)

[Ocean](https://ocean.xyz/about)

[Respondents to Bank of Canada questionnaire largely oppose creating a digital loonie](https://www.tricitynews.com/national-news/respondents-to-bank-of-canada-questionnaire-largely-oppose-creating-a-digital-loonie-7898369)

[Everyone Needs An Uncle Jim](https://bitcoinmagazine.com/culture/everyone-needs-an-uncle-jim)

[BTCPay Costa Rica case study](https://blog.btcpayserver.org/case-study-bitcoin-jungle-cr/)

[Multiple currencies for LNURL](https://twitter.com/luizfgparreira/status/1730606242190524680

[Bitcoin transaction size calculator](https://bitcoinops.org/en/tools/calc-size/)

[Delving Bitcoin Forum gains traction](https://delvingbitcoin.org/)

[Ocean no longer includes inscriptions in their block template](https://twitter.com/mononautical/status/1732230375509004622)

[Fiat denominated LNURL](https://twitter.com/lorenzo_lfm/status/1732169402215211122)

[Bitcoin Core 26.0 released](https://bitcoincore.org/en/2023/12/06/release-26.0/)

[Bitcoin Core Life Cycle](https://bitcoincore.org/en/lifecycle/)

[Privacy is next for CBDCs in Canada?](https://www.bankofcanada.ca/digitaldollar/a-digital-canadian-dollar-what-we-heard-2020-23-and-what-comes-next/)

[Expanding the Lightning network to serve billions using Liquid](https://juraj.bednar.io/en/blog-en/2023/05/07/expanding-the-lightning-network-to-serve-billions-a-quick-win-strategy/)

[Julian Figueroa @KineticFinance - BTC Content](https://fountain.fm/episode/na6PmJQFhwbZALXzCw2y)

[The Binance Crackdown Will Be an 'Unprecedented' Bonanza for Crypto Surveillance](https://www.wired.com/story/binance-settlement-transaction-histories/)

[Accept LND channel management tool](https://stacker.news/items/349505)

[Secondl1ght on encrypted messaging over the Lightning Network](https://www.youtube.com/watch?v=p5UuHwXH4kk)

[King of free speech Nostr Damus with William Casarin](https://www.youtube.com/watch?v=SAm_YM9Ovbg)

[Lamassu now shipping conversion kits for General Bytes ATMs](https://blog.lamassu.is/now-shipping-gb-conversion-kits/)

[What are all the rules related to CPFP fee bumping?](https://bitcoin.stackexchange.com/questions/120853/what-are-all-the-rules-related-to-cpfp-fee-bumping)

[BBQr - Better Bitcoin QR](https://github.com/coinkite/BBQr)

[Bitcoin Block Arrival Time Dataset](https://github.com/bitcoin-data/block-arrival-times)

[payjoin-cli: A command-line payjoin client for bitcoind in rust](https://github.com/payjoin/rust-payjoin/tree/master/payjoin-cli)

[The Challenges of Developing Non-Custodial Lightning on Mobile](https://lightningdevkit.org/blog/the-challenges-of-developing-non-custodial-lightning-on-mobile/)

[Two Lightning Attacks Analyzed: A Response to John Light](https://stacker.news/items/351788)

[Text Bitcoin to Anyone, Anywhere, Any Wallet](https://x.com/river/status/1735343963765391800)

[Ledger security incident](https://twitter.com/lopp/status/1735353894409052227)

[Will and Vanessa on the Life with Bitcoin podcast](https://x.com/lifewbitcoin/status/1731365177616961831)

[Attorney-Eyes-Only Disclosure of Heuristics Used by Government in Analyzing Blockchain Transactions](https://reason.com/volokh/2023/12/13/attorney-eyes-only-disclosure-of-heuristics-used-by-government-in-analyzing-blockchain-transactions/)

[Shakepay customer data compromised](https://x.com/shakepay/status/1735469696718164197)

[F2Pool payout transaction with 0.5 BTC in opportunity cost](https://mempool.space/tx/1a1a6fbf2ce657217790eb3957b58e3b7cc4852c0e54011289b8300e0abf1e09)

[Beyond COP28: A fresh look at bitcoin’s ESG credentials](https://www.ft.com/content/b26b5af8-0cf1-424b-bafc-d2ce4760a28c)

[Buy inbound liquidity in Phoenix wallet](https://x.com/phoenixwallet/status/1735699451770032354)

[LNbank Vulnerability Recap](https://d11n.net/lnbank-vulnerability-recap)
[Another LNbank vulnerability](https://x.com/btcpayserver/status/1739669361223172448)

[Opago Pay Lightning PoS](https://opago-pay.com/en/product/opago_lightning_pos-terminal_gen1)

[Klever Wallet: Security Incident 2023](https://www.youtube.com/watch?v=xp2PeNLUpxY)

[SSH protects the world’s most sensitive networks. It just got a lot weaker](https://arstechnica.com/security/2023/12/hackers-can-break-ssh-channel-integrity-using-novel-data-corruption-attack/)

[Murch explaining the Bitcoin Core UTXO set](https://x.com/murchandamus/status/1737122899658448934)

[SatoshiGPT](https://chat.openai.com/g/g-wNCUpwLP8-satoshigpt)

[Bitcoin ATM company Coin Cloud got hacked. Even its new owners don’t know how.](https://techcrunch.com/2023/12/12/bitcoin-atm-company-coin-cloud-got-hacked/)

[Introducing Ghost Addresses](https://amboss.tech/blog/ghost-addresses)

[Build the future of money](https://bitcoindevs.xyz/)

[This N.Y.U. Student Owns a $6 Million Crypto Mine. His Secret Is Out.](https://www.nytimes.com/2023/12/25/technology/bitrush-bitcoin-cryptocurrency-china.html)

[Eleven Free Resources To Learn Bitcoin And Sharpen Your Knowledge](https://www.forbes.com/sites/digital-assets/2023/12/27/eleven-free-resources-to-learn-bitcoin-and-sharpen-your-knowledge/)

[Why bitcoin is up by almost 150% this year - Introducing the cockroach theory of crypto](https://www.economist.com/finance-and-economics/2023/12/18/why-bitcoin-is-up-by-almost-150-this-year)

[Inscriptions: A Guide for the Ideological Maxi](https://rodarmor.com/blog/inscriptions-a-guide-for-the-ideological-maxi/)

[Inscription analytics](https://dune.com/dataalways/ordinals)

[WTF happened in February 2023? An analysis of the ordinals phenomenon](https://wtfhappenedinfeb2023.github.io/)

[v3 transaction policy for anti-pinning](https://github.com/bitcoin/bitcoin/pull/28948)

[Coinos Enables Liquid](https://x.com/coinoswallet/status/1742641753742811550)

[Aqua wallet launched](https://twitter.com/AquaBitcoin/status/1742761528451854390)

[Blink Plugin for BTCPay](https://x.com/blinkbtc/status/1742963123647058169)

[Bitwarden Heist - How to Break Into Password Vaults Without Using Passwords](https://blog.redteam-pentesting.de/2024/bitwarden-heist/)

[Tor client written in Rust](https://twitter.com/samkorn/status/1743100521429242032)

[Witness scripts being abused to bypass datacarriersize limit](https://github.com/bitcoin/bitcoin/issues/29187)

[datacarriersize: Match more datacarrying #28408](https://github.com/bitcoin/bitcoin/pull/28408)

[Rethinking Lightning - benthecarman](https://stacker.news/items/379225)

[FT Opinion: My new year resolution is bitcoin](https://www.ft.com/content/59bb430b-a5b1-4469-b05a-482b951109a2)

[Mercury Layer goes live](https://mercurylayer.com/)

[Demystifying the long and convoluted process of a Bitcoin softfork](https://www.quantumcats.xyz/bip-land)

[Mempool pinning for BRC-20](https://x.com/mononautical/status/1746196727953027205)

[Buying Lightning channels from Blocktank on Bitfinex](https://twitter.com/synonym_to/status/1747604683907379651)

[BTCPay Server 2024, The Year of Ambassadors](https://blog.btcpayserver.org/bitcoin-2024-the-year-of-ambassadors/)

[Disclosure: Btcd consensus bugs due to usage of signed transaction version](https://delvingbitcoin.org/t/disclosure-btcd-consensus-bugs-due-to-usage-of-signed-transaction-version/455)

**Comment by Liongrass** [comment]
[FTX Sold About $1B of Grayscale's Bitcoin ETF, Explaining Much of Outflow: Sources](https://www.coindesk.com/business/2024/01/22/ftx-sold-about-1b-of-grayscales-bitcoin-etf-explaining-much-of-outflow-sources/)

[Warnet simulations](https://delvingbitcoin.org/t/warnet-simulations/232)

[The Past, Present, and Future of Offline Payments](https://medium.com/breez-technology/the-past-present-and-future-of-offline-payments-1ddb46054e11)

[Stranded: How Bitcoin is Saving Wasted Energy and Expanding Financial Freedom in Africa](https://bitcoinmagazine.com/check-your-financial-privilege/stranded-bitcoin-saving-wasted-energy-in-africa)

[What happens to dust sent to a Bitcoin ETF](https://twitter.com/hongkim__/status/1750972104600904019)

[2000 lightning transactions per month at South Africa's 2nd largest retail chain](https://twitter.com/bitcoinekasi/status/1750884698178371804)

[How do half-finished blocks happen](https://mempool.space/block/00000000000000000001baf919a377ef1e01c2437c1dc5373e97013a9e09e2ac)

[How a 27-Year-Old Codebreaker Busted the Myth of Bitcoin’s Anonymity](https://www.wired.com/story/27-year-old-codebreaker-busted-myth-bitcoins-anonymity/)

**Comment by Bedframepanda** [comment]
How many Vancouver Businesses accept Bitcoin.

**Comment by Bedframepanda** [comment]
> [FTX Sold About $1B of Grayscale's Bitcoin ETF, Explaining Much of Outflow: Sources](https://www.coindesk.com/business/2024/01/22/ftx-sold-about-1b-of-grayscales-bitcoin-etf-explaining-much-of-outflow-sources/)
> 
> [Warnet simulations](https://delvingbitcoin.org/t/warnet-simulations/232)
> 
> [The Past, Present, and Future of Offline Payments](https://medium.com/breez-technology/the-past-present-and-future-of-offline-payments-1ddb46054e11)
> 
> [Stranded: How Bitcoin is Saving Wasted Energy and Expanding Financial Freedom in Africa](https://bitcoinmagazine.com/check-your-financial-privilege/stranded-bitcoin-saving-wasted-energy-in-africa)
> 
> [What happens to dust sent to a Bitcoin ETF](https://twitter.com/hongkim__/status/1750972104600904019)
> 
> [2000 lightning transactions per month at South Africa's 2nd largest retail chain](https://twitter.com/bitcoinekasi/status/1750884698178371804)
> 
> [How do half-finished blocks happen](https://mempool.space/block/00000000000000000001baf919a377ef1e01c2437c1dc5373e97013a9e09e2ac)
> 
> [How a 27-Year-Old Codebreaker Busted the Myth of Bitcoin’s Anonymity](https://www.wired.com/story/27-year-old-codebreaker-busted-myth-bitcoins-anonymity/)

How many businesses in Vancouver accept Bitcoin.
