### ISSUE TITLE
 2024-02-27 Get your links and discussion topics in!

### ISSUE THREAD

**Issue by Liongrass** [VancouverBitdevs/VancouverBitdevs.github.io#56]

**Comment by Liongrass** [comment]
[Wallet of Satoshi surpases 15 million transactions](https://twitter.com/walletofsatoshi/status/1752517658606743928)

[An upper Bound for the Probability to be able to successfully conduct a Payment on the Lightning Network](https://github.com/renepickhardt/Lightning-Network-Limitations/blob/main/likelihood-of-payment-possability/An%20upper%20Bound%20for%20the%20Probability%20to%20be%20able%20to%20successfully%20conduct%20a%20Payment%20on%20the%20Lightning%20Network.ipynb)

[NY Community Bancorp Plunges as Real Estate Risks Jolt Market](https://www.bloomberg.com/news/articles/2024-01-31/new-york-community-bancorp-slumps-on-surprise-loss-dividend-cut)

[A single node is responsible for half of the penalty transactions in January](https://forkmonitor.info/lightning)

[Watchman Privacy: Coincards - Buy Gift Cards with Monero and Bitcoin](https://fountain.fm/episode/dCvn3BxK849u76vnw8aW)

[Company that had 3 secret cryptocurrency mines must pay $400K, cease operations in Alberta](https://www.cbc.ca/news/canada/edmonton/green-block-mining-settlement-utilities-commission-1.7099790)

[Vanity Bitcoin transactions](https://twitter.com/keithmukai/status/1753178714441941392)

[Coinos allows users to configure auto-withdrawals onchain](https://twitter.com/coinoswallet/status/1753182855226912833)

[New York Community Bank stock collapse](https://twitter.com/KobeissiLetter/status/1754964227511509494)

[Damus & Nostr: Revolutionizing Bitcoin in Web3 | William Casarin](https://www.youtube.com/watch?v=CaAx1DiBjRQ)

[Introducing Citrea: Bitcoin’s First ZK Rollup](https://www.blog.citrea.xyz/introducing-citrea/)

["Fake income" mortgages fuel Toronto Real Estate Bubble: HSBC Bank Leaks](https://www.thebureau.news/p/fake-chinese-income-mortgages-fuel)


[Crypto firm fails in court bid to force BC Hydro to power it](https://globalnews.ca/news/10274658/bc-hydro-crypto-pause/)

[Take Your Business Global by Accepting Bitcoin (Adam & Cole, Coinos)](https://beyondtheprice.substack.com/p/take-your-business-global-by-accepting)

[chanbackup+sweeper: periodically checkpoint active sweeper state using p2p encrypted peer storage feature](https://github.com/lightningnetwork/lnd/issues/8472)

[Add a BIP which resolves human readable names into payment info](https://github.com/bitcoin/bips/pull/1551)

[Bitcoin Dev mailing list now on Google Groups](https://groups.google.com/g/bitcoindev)

[Lightning transactions with v3 and ephemeral anchors](https://delvingbitcoin.org/t/lightning-transactions-with-v3-and-ephemeral-anchors/418/1)

[What Bitcoin Did: The Hidden Cost of Money with Seb Bunney](https://www.youtube.com/watch?v=DnBuIla9nGU)

[Perpetually KYC’d Coins Using Evil Covenants](https://delvingbitcoin.org/t/perpetually-kycd-coins-using-evil-covenants/556)

[interactive-tx: Add dual-funding flow, using the interactive tx protocol (feature 28/29) #851](https://github.com/lightning/bolts/pull/851)

[Awesome L402](https://github.com/Fewsats/awesome-L4020)

[Bitwise moves ETF to Segwit addresses](https://twitter.com/BitwiseInvest/status/1757813223536103568)

[iShares ETF hits US$5 billion in assets in five weeks](https://twitter.com/NateGeraci/status/1757627837626867810)

[A lightning address for every npub](https://primal.net/e/note1q5767jm5xp07d23u6qx038dxrazp3hst5wk5np3cnw4wcaml9vwsz8xuhk)

[Simplest Ark Explanation](https://gist.github.com/RubenSomsen/a394beb1dea9e47e981216768e007454?permalink_comment_id=4633382#file-_simplest_ark-md)

[Binance sets cap on USDT for Nigeria](https://twitter.com/mikaelcbernard/status/1760023906826478001)

[Braiins offers Lightning payouts](https://twitter.com/braiinsmining/status/1760319741560856983)

[Exodus Bitcoin Wallet: $490K Swindle](https://popey.com/blog/2024/02/exodus-bitcoin-wallet-490k-swindle/)

[Bitcoin Magazine Editorial Policy On Bitcoin Layer 2s (L2s)](https://bitcoinmagazine.com/press-releases/bitcoin-magazine-editorial-policy-on-bitcoin-layer-2s-l2s)

[Amboss launched Lightning analytics tools](https://rpo.dev/)

[Marathon mining odd transactions](https://twitter.com/mononautical/status/1760746059956187414)

[Bitcoin ossification debate](https://twitter.com/TFTC21/status/1759704333736878289)

[Swaproot: cheaper and more private on-chain deposits on Phoenix](https://acinq.co/blog/phoenix-swaproot)

[Wave of proposed "L2s"](https://twitter.com/davidfbailey/status/1760050396414775596)

[Coinbase Commerce drops Bitcoin payments](https://twitter.com/lauren_dowling_/status/1758985684340322656)

[Satoshi - Sirius emails 2009-2011](https://mmalmi.github.io/satoshi/)

[Short explanation of how Bitcoin Core ranks unconfirmed transactions](https://twitter.com/mononautical/status/1761574082569527555)

**Comment by positiveblue** [comment]
[Using LNC with your Aperture server](https://github.com/lightninglabs/aperture/pull/107)

["standard" encoding for invoice metadata](https://github.com/lightningnetwork/lnd/issues/8445)
